name: kaggle-keep-alive-service

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping-service:
    runs-on: ubuntu-latest

    steps:
      - name: curl request to ping kaggle api service
        run: curl -sSf https://kaggle-api.onrender.com/
